export {default as Navbar} from './navbar/Navbar';
export {default as Footer} from './footer/Footer';
export {default as Homepage} from './homepage/Homepage';
export {default as Register} from './register/Register';
export {default as SignIn} from './signIn/SignIn';
export {default as ServicesPage} from './servicesPage/ServicesPage';
export {default as ContactPage} from './contactPage/contactPage';
export {default as AboutPage} from './aboutPage/AboutPage';
export {default as Contacts} from './contacts/Contacts';